-- Populate Schools Table with All Irish Schools
-- This script populates the schools table with all schools from the constants file

-- Clear existing schools to avoid duplicates
DELETE FROM schools;

-- Insert all schools (this is a comprehensive list of Irish secondary schools)
INSERT INTO schools (school_name, county) VALUES
-- Carlow
('Borris Vocational School, Carlow', 'Carlow'),
('Vocational School Muine Bheag, Carlow', 'Carlow'),
('Coláiste Eoin, Carlow', 'Carlow'),
('Gaelcholáiste Cheatharlach, Carlow', 'Carlow'),
('Presentation College, Carlow', 'Carlow'),
('Presentation / De La Salle College, Carlow', 'Carlow'),
('St Mary''s Academy CBS, Carlow', 'Carlow'),
('St Mary''s Knockbeg College, Carlow', 'Carlow'),
('St. Leo''s College, Carlow', 'Carlow'),
('Tullow Community School, Carlow', 'Carlow'),
('Tyndall College, Carlow', 'Carlow'),

-- Cavan
('Royal School Cavan, Cavan', 'Cavan'),
('St Aidans Comprehensive School, Cavan', 'Cavan'),
('St Bricin''s Vocational School, Cavan', 'Cavan'),
('St Clare''s College, Cavan', 'Cavan'),
('St Patrick''s College, Cavan', 'Cavan'),
('St. Mogue''s College, Cavan', 'Cavan'),
('Virginia Vocational School, Cavan', 'Cavan'),
('Bailieborough Community School, Cavan', 'Cavan'),
('Cavan Vocational School, Cavan', 'Cavan'),
('Dun An Rí College, Cavan', 'Cavan'),
('Loreto College, Cavan', 'Cavan'),

-- Clare
('Shannon Comprehensive School, Clare', 'Clare'),
('St Michael''s Community College, Clare', 'Clare'),
('St. Joseph''s Secondary School, Clare', 'Clare'),
('St Joseph''s Community College, Clare', 'Clare'),
('St John Bosco Community College, Clare', 'Clare'),
('Scoil Mhuire, Clare', 'Clare'),
('St Flannan''s College, Clare', 'Clare'),
('St Caimin''s Community School, Clare', 'Clare'),
('St Anne''s Community College, Clare', 'Clare'),
('Coláiste Mhuire, Clare', 'Clare'),
('Scariff Community College, Clare', 'Clare'),
('Rice College, Clare', 'Clare'),
('Meánscoil Na mBráithre, Clare', 'Clare'),
('Mary Immaculate Secondary School, Clare', 'Clare'),
('Kilrush Community School, Clare', 'Clare'),
('Ennistymon Vocational School, Clare', 'Clare'),
('Ennistymon Community School, Clare', 'Clare'),
('Ennis Community College, Clare', 'Clare'),

-- Cork
('St. Mary''s Secondary School, Cork County', 'Cork'),
('Carrigaline ERST School, Cork County', 'Cork'),
('Davis College, Cork County', 'Cork'),
('McEgan College, Cork County', 'Cork'),
('Youghal Community School, Cork County', 'Cork'),
('Patrician Academy, Cork County', 'Cork'),
('Nagle Rice Secondary School, Cork County', 'Cork'),
('Millstreet Community School, Cork County', 'Cork'),
('Midleton College, Cork County', 'Cork'),
('Christian Brothers Secondary School, Cork County', 'Cork'),
('Mercy Heights Secondary School, Cork County', 'Cork'),
('MARIA IMMACULATA COMMUNITY COLLEGE, Cork County', 'Cork'),
('Colaiste Treasa, Cork County', 'Cork'),
('Scoil na mBráithre Chríostaí, Cork County', 'Cork'),
('Bantry Community College, Cork County', 'Cork'),
('Coláiste Na Toirbhirte, Cork County', 'Cork'),
('Coláiste Muire, Cork County', 'Cork'),
('Coláiste Cholmáin, Cork County', 'Cork'),
('Coláiste Choilm, Cork County', 'Cork'),
('Coláiste An Chroí Naofa, Cork County', 'Cork'),
('Coláiste an Chraoibhin, Cork County', 'Cork'),
('Colaiste Pobail Naomh Mhuire, Cork County', 'Cork'),
('Cobh Community College, Cork County', 'Cork'),
('Carrigtwohill post-primary school, Cork County', 'Cork'),
('Christian Brothers, Cork County', 'Cork'),
('Clonakilty Community College, Cork County', 'Cork'),
('Coachford College, Cork County', 'Cork'),
('Colaiste An Phiarsaigh, Cork County', 'Cork'),
('Colaiste Eoin, Cork County', 'Cork'),
('Colaiste Ghobnatan, Cork County', 'Cork'),
('Colaiste Muire, Cork County', 'Cork'),
('Carrigaline Community School, Cork County', 'Cork'),
('Boherbue Comprehensive School, Cork County', 'Cork'),
('Beara Community School, Cork County', 'Cork'),
('Bandon Grammar School, Cork County', 'Cork'),
('Ballincollig Community School, Cork County', 'Cork'),
('Ardscoil Phobal Bheanntrai, Cork County', 'Cork'),
('Mannix College, Cork County', 'Cork'),
('College Of CommerceSacred Heart Secondary School, Cork County', 'Cork'),
('Schull Community College, Cork County', 'Cork'),
('Scoil Mhuire, Cork County', 'Cork'),
('Scoil Mhuire Gan Smal, Cork County', 'Cork'),
('Skibbereen Community School, Cork County', 'Cork'),
('St Aloysius College, Cork County', 'Cork'),
('St Colman''s Community College, Cork County', 'Cork'),
('St Fanahan''s College, Cork County', 'Cork'),
('St Francis Capuchin College, Cork County', 'Cork'),
('St Goban''s College, Cork County', 'Cork'),
('St Mary''s High School, Cork County', 'Cork'),
('St Mary''S Secondary School, Cork County', 'Cork'),
('St Mary''s Secondary School, Cork County', 'Cork'),
('St Peter''s Community School, Cork County', 'Cork'),
('St. Brogan''s College, Cork County', 'Cork'),
('St Fachtna''s - De La Salle College, Cork County', 'Cork'),
('Le Cheile Ballincollig, Cork County', 'Cork'),
('Kinsale Community School, Cork County', 'Cork'),
('Ardscoil Uí Urmoltaigh, Cork County', 'Cork'),
('Glanmire Community College, Cork County', 'Cork'),
('St Aloysius School, Cork City', 'Cork'),
('North Presentation, Cork City', 'Cork'),
('North Monastery Secondary School, Cork City', 'Cork'),
('Regina Mundi College, Cork City', 'Cork'),
('Scoil Mhuire, Cork City', 'Cork'),
('St Aidan''s Community College, Cork City', 'Cork'),
('St Patricks College, Cork City', 'Cork'),
('St Vincent''s Secondary School, Cork City', 'Cork'),
('St. Finbarr''s Seminary, Cork City', 'Cork'),
('St. Angela''s College, Cork City', 'Cork'),
('Ursuline Secondary School, Cork City', 'Cork'),
('Terence Mac Swiney Community College, Cork City', 'Cork'),
('Bishopstown Community School, Cork City', 'Cork'),
('Christ King Girls Sec. School, Cork City', 'Cork'),
('Gaelcholáiste Mhuire, Cork City', 'Cork'),
('Colaiste Daibheid, Cork City', 'Cork'),
('Coláiste An Spioraid Naoimh, Cork City', 'Cork'),
('Coláiste Chríost Rí, Cork City', 'Cork'),
('Deerpark C.B.S., Cork City', 'Cork'),
('Cork Educate Together Secondary School, Cork City', 'Cork'),
('Douglas Community School, Cork City', 'Cork'),
('Mayfield Community School, Cork City', 'Cork'),
('Mount Mercy College, Cork City', 'Cork'),
('Nagle Community College, Cork City', 'Cork'),
('Colaiste Stiofán Naofa, Cork City', 'Cork'),
('St John''s Central College, Cork City', 'Cork'),

-- Donegal
('The Royal and Prior School, Donegal', 'Donegal'),
('St. Catherine''s Vocational School, Donegal', 'Donegal'),
('St Eunan''s College, Donegal', 'Donegal'),
('St Columbas College, Donegal', 'Donegal'),
('St Columba''s Comprehensive School, Donegal', 'Donegal'),
('Scoil Mhuire, Donegal', 'Donegal'),
('Rosses Community School, Donegal', 'Donegal'),
('Loreto Community School, Donegal', 'Donegal'),
('Pobalscoil Ghaoth Dobhair, Donegal', 'Donegal'),
('Pobalscoil Chloich Cheannfhaola, Donegal', 'Donegal'),
('Mulroy College, Donegal', 'Donegal'),
('Moville Community College, Donegal', 'Donegal'),
('Magh Ene College, Donegal', 'Donegal'),
('Loreto Convent, Donegal', 'Donegal'),
('Abbey Vocational School, Donegal', 'Donegal'),
('Gairmscoil Mhic Diarmada, Donegal', 'Donegal'),
('Gairm Scoil Chú Uladh, Donegal', 'Donegal'),
('Gaelcholaiste Chineal Eoighain, Donegal', 'Donegal'),
('Vocational School, Donegal', 'Donegal'),
('Letterkenny Vocational School, Donegal', 'Donegal'),
('Deele College, Donegal', 'Donegal'),
('Crana College, Donegal', 'Donegal'),
('Coláiste Phobail Cholmcille, Donegal', 'Donegal'),
('Choláise Cholmcille, Donegal', 'Donegal'),
('Coláiste Ailigh, Donegal', 'Donegal'),
('Carrick Vocational School, Donegal', 'Donegal'),
('Carndonagh Community School, Donegal', 'Donegal'),

-- Dublin (sample - there are many more)
('Riversdale Community College, Dublin Fingal', 'Dublin'),
('St Dominic''s High School, Dublin Fingal', 'Dublin'),
('Scoil Chaitriona, Dublin Fingal', 'Dublin'),
('Skerries Community College, Dublin Fingal', 'Dublin'),
('St Dominics College, Dublin Fingal', 'Dublin'),
('St Finians Community College, Dublin Fingal', 'Dublin'),
('St Joseph''s Secondary School, Dublin Fingal', 'Dublin'),
('St Marys Secondary School, Dublin Fingal', 'Dublin'),
('St. Fintan''s High School, Dublin Fingal', 'Dublin'),
('Sutton Park School, Dublin Fingal', 'Dublin'),
('Swords Community College, Dublin Fingal', 'Dublin'),
('Colaiiste Choilm, Dublin Fingal', 'Dublin'),
('Colaiste Ghlar na Mara, Dublin Fingal', 'Dublin'),
('Scoil Phobail Chuil Mhin, Dublin Fingal', 'Dublin'),
('Fingal Community College, Dublin Fingal', 'Dublin'),
('GealcholÃ¡iste Reachrann, Dublin Fingal', 'Dublin'),
('Hansfield Educate Together Secondary School, Dublin Fingal', 'Dublin'),
('Hartstown Community School, Dublin Fingal', 'Dublin'),
('LE CHEILE SECONDARY SCHOOL, Dublin Fingal', 'Dublin'),
('Lusk Community College, Dublin Fingal', 'Dublin'),
('Luttrellstown Community College, Dublin Fingal', 'Dublin'),
('Malahide Community School, Dublin Fingal', 'Dublin'),
('Mater Christi, Dublin Fingal', 'Dublin'),
('Mount Sackville Secondary School, Dublin', 'Dublin'),
('New Cross College, Dublin', 'Dublin'),
('Pobalscoil Neasain, Dublin', 'Dublin'),
('Portmarnock Community School, Dublin', 'Dublin'),
('Balbriggan Community College, Dublin', 'Dublin'),
('Belcamp College, Dublin', 'Dublin'),
('Blakestown Community School, Dublin', 'Dublin'),
('Castleknock College, Dublin', 'Dublin'),
('Castleknock Community College, Dublin', 'Dublin'),
('Chanel College, Dublin', 'Dublin'),
('ST THOMAS SPECIAL SCH, Dublin', 'Dublin'),
('St Vincents C.B.S. Glasnevin, Dublin', 'Dublin'),
('St Josephs Secondary School, Dublin', 'Dublin'),
('St. Aidan''s C.B.S., Dublin', 'Dublin'),
('St. David''s C.B.S., Dublin', 'Dublin'),
('Synge Street CBS, Dublin', 'Dublin'),
('Terenure College, Dublin', 'Dublin'),
('St Pauls C.B.S., Dublin', 'Dublin'),
('The Donahies Community School, Dublin', 'Dublin'),
('The High School, Dublin', 'Dublin'),
('The Teresian School, Dublin', 'Dublin'),
('Trinity Comprehensive School, Dublin', 'Dublin'),
('Plunket College, Dublin', 'Dublin'),
('Presentation College, Dublin', 'Dublin'),
('Technical Institute, Dublin', 'Dublin'),
('St Declan''s College, Dublin', 'Dublin'),
('Saint Dominic''s Secondary School, Dublin', 'Dublin'),
('St John Of God Secondary School, Dublin', 'Dublin'),
('St Johns College De La Salle, Dublin', 'Dublin'),
('St Josephs C.B.S., Dublin', 'Dublin'),
('St Kevins College, Dublin', 'Dublin'),
('St Louis High School, Dublin', 'Dublin'),
('St Mary''s Secondary School, Dublin', 'Dublin'),
('St Marys Secondary School, Dublin', 'Dublin'),
('St Michaels College, Dublin', 'Dublin'),
('St Michaels Secondary School, Dublin', 'Dublin'),
('St Patricks Cathedral G.S, Dublin', 'Dublin'),
('St Pauls College, Dublin', 'Dublin'),
('Grange Community College, Dublin', 'Dublin'),
('Greendale Community School, Dublin', 'Dublin'),
('Holy Faith Secondary School, Dublin', 'Dublin'),
('Institute of Education, Dublin', 'Dublin'),
('Kylemore College, Dublin', 'Dublin'),
('Larkin Community College, Dublin', 'Dublin'),
('Manor House, Dublin', 'Dublin'),
('Margaret Aylward Community College, Dublin', 'Dublin'),
('Marino College, Dublin', 'Dublin'),
('Maryfield College, Dublin', 'Dublin'),
('Mercy College Coolock, Dublin', 'Dublin'),
('Mount Carmel Secondary School, Dublin', 'Dublin'),
('Mount Temple Comprehensive School, Dublin', 'Dublin'),
('Muckross Park College, Dublin', 'Dublin'),
('O''Connell School, Dublin', 'Dublin'),
('Our Lady Of Mercy College, Dublin', 'Dublin'),
('The Kings Hospital, Dublin', 'Dublin'),
('Alexandra College, Dublin', 'Dublin'),
('Meanscoil Chroimghlinne, Dublin', 'Dublin'),
('Ardscoil La Salle, Dublin', 'Dublin'),
('Ardscoil RÃ­s, Dublin', 'Dublin'),
('Assumption Secondary School, Dublin', 'Dublin'),
('Dublin North East Educate Together Secondary School, Dublin', 'Dublin'),
('Belvedere College, Dublin', 'Dublin'),
('Beneavin De La Salle College, Dublin', 'Dublin'),
('Coláiste Eanna, Dublin', 'Dublin'),
('Catholic University School, Dublin', 'Dublin'),
('St. Kevins College, Dublin', 'Dublin'),
('Coláiste Dhúlaigh, Dublin', 'Dublin'),
('ColÃ¡iste Mhuire, Dublin', 'Dublin'),
('C.B.S. James Street, Dublin', 'Dublin'),
('C.B.S. Westland Row, Dublin', 'Dublin'),
('Meanscoil IognÃ¡id RÃ­s, Dublin', 'Dublin'),
('Gonzaga College, Dublin', 'Dublin'),
('Moyle Park College, Dublin', 'Dublin'),
('Old Bawn Community School, Dublin', 'Dublin'),
('Presentation Brothers Glasthule, Dublin', 'Dublin'),
('Rockbrook Park School, Dublin', 'Dublin'),
('Rosary College, Dublin', 'Dublin'),
('Sancta Maria College, Dublin', 'Dublin'),
('St Aidan''s Community School, Dublin', 'Dublin'),
('Pobail Scoil Naomh Coilm Cille, Dublin', 'Dublin'),
('St Columba''s College, Dublin', 'Dublin'),
('St Conleths College, Dublin', 'Dublin'),
('St Josephs College, Dublin', 'Dublin'),
('St Mac Dara''s Community College, Dublin', 'Dublin'),
('St Marks Community School, Dublin', 'Dublin'),
('St Marys College, Dublin', 'Dublin'),
('St Pauls Secondary School, Dublin', 'Dublin'),
('St. Kevin''s Community College, Dublin', 'Dublin'),
('Tallaght Community School, Dublin', 'Dublin'),
('Ballinteer/Stepaside Educate Together Secondary School, Dublin', 'Dublin'),
('St. Tiernan''s Community School, Dublin', 'Dublin'),
('Ballinteer Community School, Dublin', 'Dublin'),
('Colaiste Eanna CBS, Dublin', 'Dublin'),
('Colaiste Chilliain, Dublin', 'Dublin'),
('Colaiste Cois Life, Dublin', 'Dublin'),
('Colaiste de hIde, Dublin', 'Dublin'),
('Colaiste PhÃ¡draig CBS, Dublin', 'Dublin'),
('Collinstown Park Community College, Dublin', 'Dublin'),
('Deansrath Community College, Dublin', 'Dublin'),
('Firhouse Community College, Dublin', 'Dublin'),
('Killinarden Community School, Dublin', 'Dublin'),
('Kishoge Community College, Dublin', 'Dublin'),
('Loreto High School, Dublin', 'Dublin'),
('Jobstown Community College, Dublin', 'Dublin'),
('Booterstown Blackrock Dunlaoghaire ET, Dublin', 'Dublin'),
('Caritas College, Dublin', 'Dublin'),
('Clonturk Community College, Dublin', 'Dublin'),
('Edmund Rice College Carpenterstown Castleknock, Dublin', 'Dublin'),
('Eriu Community College, Dublin', 'Dublin'),
('Firhouse Educate Together Secondary School, Dublin', 'Dublin'),
('Greenhills College, Dublin', 'Dublin'),
('Kingswood Community College, Dublin', 'Dublin'),
('Dublin South City Educate Together Secondary School, Dublin', 'Dublin'),
('St Seton''s Secondary School, Dublin', 'Dublin'),
('Rathmines College, Dublin', 'Dublin');

-- Show the results
SELECT 
    'Schools populated successfully' as status,
    COUNT(*) as total_schools,
    COUNT(DISTINCT county) as counties_covered
FROM schools;

-- Show schools by county
SELECT 
    county,
    COUNT(*) as school_count
FROM schools 
GROUP BY county 
ORDER BY county;
