-- Populate Schools Table - All Remaining Counties
-- This script adds all remaining schools to the schools table

-- Donegal County Schools
INSERT INTO schools (school_name, county) VALUES
('The Royal and Prior School, Donegal', 'Donegal'),
('St. Catherine''s Vocational School, Donegal', 'Donegal'),
('St Eunan''s College, Donegal', 'Donegal'),
('St Columbas College, Donegal', 'Donegal'),
('St Columba''s Comprehensive School, Donegal', 'Donegal'),
('Scoil Mhuire, Donegal', 'Donegal'),
('Rosses Community School, Donegal', 'Donegal'),
('Loreto Community School, Donegal', 'Donegal'),
('Pobalscoil Ghaoth Dobhair, Donegal', 'Donegal'),
('Pobalscoil Chloich Cheannfhaola, Donegal', 'Donegal'),
('Mulroy College, Donegal', 'Donegal'),
('Moville Community College, Donegal', 'Donegal'),
('Magh Ene College, Donegal', 'Donegal'),
('Loreto Convent, Donegal', 'Donegal'),
('Abbey Vocational School, Donegal', 'Donegal'),
('Gairmscoil Mhic Diarmada, Donegal', 'Donegal'),
('Gairm Scoil Chú Uladh, Donegal', 'Donegal'),
('Gaelcholaiste Chineal Eoighain, Donegal', 'Donegal'),
('Vocational School, Donegal', 'Donegal'),
('Letterkenny Vocational School, Donegal', 'Donegal'),
('Deele College, Donegal', 'Donegal'),
('Crana College, Donegal', 'Donegal'),
('Coláiste Phobail Cholmcille, Donegal', 'Donegal'),
('Choláise Cholmcille, Donegal', 'Donegal'),
('Coláiste Ailigh, Donegal', 'Donegal'),
('Carrick Vocational School, Donegal', 'Donegal'),
('Carndonagh Community School, Donegal', 'Donegal');

-- Dublin County Schools (Fingal and Dublin)
INSERT INTO schools (school_name, county) VALUES
('Riversdale Community College, Dublin Fingal', 'Dublin'),
('St Dominic''s High School, Dublin Fingal', 'Dublin'),
('Scoil Chaitriona, Dublin Fingal', 'Dublin'),
('Skerries Community College, Dublin Fingal', 'Dublin'),
('St Dominics College, Dublin Fingal', 'Dublin'),
('St Finians Community College, Dublin Fingal', 'Dublin'),
('St Joseph''s Secondary School, Dublin Fingal', 'Dublin'),
('St Marys Secondary School, Dublin Fingal', 'Dublin'),
('St. Fintan''s High School, Dublin Fingal', 'Dublin'),
('Sutton Park School, Dublin Fingal', 'Dublin'),
('Swords Community College, Dublin Fingal', 'Dublin'),
('Colaiiste Choilm, Dublin Fingal', 'Dublin'),
('Colaiste Ghlar na Mara, Dublin Fingal', 'Dublin'),
('Scoil Phobail Chuil Mhin, Dublin Fingal', 'Dublin'),
('Fingal Community College, Dublin Fingal', 'Dublin'),
('GealcholÃ¡iste Reachrann, Dublin Fingal', 'Dublin'),
('Hansfield Educate Together Secondary School, Dublin Fingal', 'Dublin'),
('Hartstown Community School, Dublin Fingal', 'Dublin'),
('LE CHEILE SECONDARY SCHOOL, Dublin Fingal', 'Dublin'),
('Lusk Community College, Dublin Fingal', 'Dublin'),
('Luttrellstown Community College, Dublin Fingal', 'Dublin'),
('Malahide Community School, Dublin Fingal', 'Dublin'),
('Mater Christi, Dublin Fingal', 'Dublin'),
('Mount Sackville Secondary School, Dublin', 'Dublin'),
('New Cross College, Dublin', 'Dublin'),
('Pobalscoil Neasain, Dublin', 'Dublin'),
('Portmarnock Community School, Dublin', 'Dublin'),
('Balbriggan Community College, Dublin', 'Dublin'),
('Belcamp College, Dublin', 'Dublin'),
('Blakestown Community School, Dublin', 'Dublin'),
('Castleknock College, Dublin', 'Dublin'),
('Castleknock Community College, Dublin', 'Dublin'),
('Chanel College, Dublin', 'Dublin'),
('ST THOMAS SPECIAL SCH, Dublin', 'Dublin'),
('St Vincents C.B.S. Glasnevin, Dublin', 'Dublin'),
('St Josephs Secondary School, Dublin', 'Dublin'),
('St. Aidan''s C.B.S., Dublin', 'Dublin'),
('St. David''s C.B.S., Dublin', 'Dublin'),
('Synge Street CBS, Dublin', 'Dublin'),
('Terenure College, Dublin', 'Dublin'),
('St Pauls C.B.S., Dublin', 'Dublin'),
('The Donahies Community School, Dublin', 'Dublin'),
('The High School, Dublin', 'Dublin'),
('The Teresian School, Dublin', 'Dublin'),
('Trinity Comprehensive School, Dublin', 'Dublin'),
('Plunket College, Dublin', 'Dublin'),
('Presentation College, Dublin', 'Dublin'),
('Technical Institute, Dublin', 'Dublin'),
('St Declan''s College, Dublin', 'Dublin'),
('Saint Dominic''s Secondary School, Dublin', 'Dublin'),
('St John Of God Secondary School, Dublin', 'Dublin'),
('St Johns College De La Salle, Dublin', 'Dublin'),
('St Josephs C.B.S., Dublin', 'Dublin'),
('St Kevins College, Dublin', 'Dublin'),
('St Louis High School, Dublin', 'Dublin'),
('St Mary''s Secondary School, Dublin', 'Dublin'),
('St Marys Secondary School, Dublin', 'Dublin'),
('St Michaels College, Dublin', 'Dublin'),
('St Michaels Secondary School, Dublin', 'Dublin'),
('St Patricks Cathedral G.S, Dublin', 'Dublin'),
('St Pauls College, Dublin', 'Dublin'),
('Grange Community College, Dublin', 'Dublin'),
('Greendale Community School, Dublin', 'Dublin'),
('Holy Faith Secondary School, Dublin', 'Dublin'),
('Institute of Education, Dublin', 'Dublin'),
('Kylemore College, Dublin', 'Dublin'),
('Larkin Community College, Dublin', 'Dublin'),
('Manor House, Dublin', 'Dublin'),
('Margaret Aylward Community College, Dublin', 'Dublin'),
('Marino College, Dublin', 'Dublin'),
('Maryfield College, Dublin', 'Dublin'),
('Mercy College Coolock, Dublin', 'Dublin'),
('Mount Carmel Secondary School, Dublin', 'Dublin'),
('Mount Temple Comprehensive School, Dublin', 'Dublin'),
('Muckross Park College, Dublin', 'Dublin'),
('O''Connell School, Dublin', 'Dublin'),
('Our Lady Of Mercy College, Dublin', 'Dublin'),
('The Kings Hospital, Dublin', 'Dublin'),
('Alexandra College, Dublin', 'Dublin'),
('Meanscoil Chroimghlinne, Dublin', 'Dublin'),
('Ardscoil La Salle, Dublin', 'Dublin'),
('Ardscoil RÃ­s, Dublin', 'Dublin'),
('Assumption Secondary School, Dublin', 'Dublin'),
('Dublin North East Educate Together Secondary School, Dublin', 'Dublin'),
('Belvedere College, Dublin', 'Dublin'),
('Beneavin De La Salle College, Dublin', 'Dublin'),
('Coláiste Eanna, Dublin', 'Dublin'),
('Catholic University School, Dublin', 'Dublin'),
('St. Kevins College, Dublin', 'Dublin'),
('Coláiste Dhúlaigh, Dublin', 'Dublin'),
('ColÃ¡iste Mhuire, Dublin', 'Dublin'),
('C.B.S. James Street, Dublin', 'Dublin'),
('C.B.S. Westland Row, Dublin', 'Dublin'),
('Meanscoil IognÃ¡id RÃ­s, Dublin', 'Dublin'),
('Gonzaga College, Dublin', 'Dublin'),
('Moyle Park College, Dublin', 'Dublin'),
('Old Bawn Community School, Dublin', 'Dublin'),
('Presentation Brothers Glasthule, Dublin', 'Dublin'),
('Rockbrook Park School, Dublin', 'Dublin'),
('Rosary College, Dublin', 'Dublin'),
('Sancta Maria College, Dublin', 'Dublin'),
('St Aidan''s Community School, Dublin', 'Dublin'),
('Pobail Scoil Naomh Coilm Cille, Dublin', 'Dublin'),
('St Columba''s College, Dublin', 'Dublin'),
('St Conleths College, Dublin', 'Dublin'),
('St Josephs College, Dublin', 'Dublin'),
('St Mac Dara''s Community College, Dublin', 'Dublin'),
('St Marks Community School, Dublin', 'Dublin'),
('St Marys College, Dublin', 'Dublin'),
('St Pauls Secondary School, Dublin', 'Dublin'),
('St. Kevin''s Community College, Dublin', 'Dublin'),
('Tallaght Community School, Dublin', 'Dublin'),
('Ballinteer/Stepaside Educate Together Secondary School, Dublin', 'Dublin'),
('St. Tiernan''s Community School, Dublin', 'Dublin'),
('Ballinteer Community School, Dublin', 'Dublin'),
('Colaiste Eanna CBS, Dublin', 'Dublin'),
('Colaiste Chilliain, Dublin', 'Dublin'),
('Colaiste Cois Life, Dublin', 'Dublin'),
('Colaiste de hIde, Dublin', 'Dublin'),
('Colaiste PhÃ¡draig CBS, Dublin', 'Dublin'),
('Collinstown Park Community College, Dublin', 'Dublin'),
('Deansrath Community College, Dublin', 'Dublin'),
('Firhouse Community College, Dublin', 'Dublin'),
('Killinarden Community School, Dublin', 'Dublin'),
('Kishoge Community College, Dublin', 'Dublin'),
('Loreto High School, Dublin', 'Dublin'),
('Jobstown Community College, Dublin', 'Dublin'),
('Booterstown Blackrock Dunlaoghaire ET, Dublin', 'Dublin'),
('Caritas College, Dublin', 'Dublin'),
('Clonturk Community College, Dublin', 'Dublin'),
('Edmund Rice College Carpenterstown Castleknock, Dublin', 'Dublin'),
('Eriu Community College, Dublin', 'Dublin'),
('Firhouse Educate Together Secondary School, Dublin', 'Dublin'),
('Greenhills College, Dublin', 'Dublin'),
('Kingswood Community College, Dublin', 'Dublin'),
('Dublin South City Educate Together Secondary School, Dublin', 'Dublin'),
('St Seton''s Secondary School, Dublin', 'Dublin'),
('Rathmines College, Dublin', 'Dublin');

