export const SCHOOLS = [
  // Carlow
  'Borris Vocational School, Carlow',
  'Vocational School Muine Bheag, Carlow',
  'Coláiste Eoin, Carlow',
  'Gaelcholáiste Cheatharlach, Carlow',
  'Presentation College, Carlow',
  'Presentation / De La Salle College, Carlow',
  'St Mary\'s Academy CBS, Carlow',
  'St Mary\'s Knockbeg College, Carlow',
  'St. Leo\'s College, Carlow',
  'Tullow Community School, Carlow',
  'Tyndall College, Carlow',


  // Cavan
  'Royal School Cavan, Cavan',
  'St Aidans Comprehensive School, Cavan',
  'St Bricin\'s Vocational School, Cavan',
  'St Clare\'s College, Cavan',
  'St Patrick\'s College, Cavan',
  'St. Mogue\'s College, Cavan',
  'Virginia Vocational School, Cavan',
  'Bailieborough Community School, Cavan',
  'Cavan Vocational School, Cavan',
  'Dun An Rí College, Cavan',
  'Loreto College, Cavan',


  // Clare
  'Shannon Comprehensive School, Clare',
  'St Michael\'s Community College, Clare',
  'St. Joseph\'s Secondary School, Clare',
  'St Joseph\'s Community College, Clare',
  'St John Bosco Community College, Clare',
  'Scoil Mhuire, Clare',
  'St Flannan\'s College, Clare',
  'St Caimin\'s Community School, Clare',
  'St Anne\'s Community College, Clare',
  'Coláiste Mhuire, Clare',
  'Scariff Community College, Clare',
  'Rice College, Clare',
  'Meánscoil Na mBráithre, Clare',
  'Mary Immaculate Secondary School, Clare',
  'Kilrush Community School, Clare',
  'Ennistymon Vocational School, Clare',
  'Ennistymon Community School, Clare',
  'Ennis Community College, Clare',


  // Cork
  'St. Mary\'s Secondary School, Cork County',
  'Carrigaline ERST School, Cork County',
  'Davis College, Cork County',
  'McEgan College, Cork County',
  'Youghal Community School, Cork County',
  'Patrician Academy, Cork County',
  'Nagle Rice Secondary School, Cork County',
  'Millstreet Community School, Cork County',
  'Midleton College, Cork County',
  'Christian Brothers Secondary School, Cork County',
  'Mercy Heights Secondary School, Cork County',
  'MARIA IMMACULATA COMMUNITY COLLEGE, Cork County',
  'Colaiste Treasa, Cork County',
  'Scoil na mBráithre Chríostaí, Cork County',
  'Bantry Community College, Cork County',
  'Coláiste Na Toirbhirte, Cork County',
  'Coláiste Muire, Cork County',
  'Coláiste Cholmáin, Cork County',
  'Coláiste Choilm, Cork County',
  'Coláiste An Chroí Naofa, Cork County',
  'Coláiste an Chraoibhin, Cork County',
  'Colaiste Pobail Naomh Mhuire, Cork County',
  'Cobh Community College, Cork County',
  'Carrigtwohill post-primary school, Cork County',
  'Christian Brothers, Cork County',
  'Christian Brothers Secondary School, Cork County',
  'Clonakilty Community College, Cork County',
  'Coachford College, Cork County',
  'Colaiste An Phiarsaigh, Cork County',
  'Colaiste Eoin, Cork County',
  'Colaiste Ghobnatan, Cork County',
  'Colaiste Muire, Cork County',
  'Carrigaline Community School, Cork County',
  'Boherbue Comprehensive School, Cork County',
  'Beara Community School, Cork County',
  'Bandon Grammar School, Cork County',
  'Ballincollig Community School, Cork County',
  'Ardscoil Phobal Bheanntrai, Cork County',
  'Mannix College, Cork County',
  'College Of CommerceSacred Heart Secondary School, Cork County',
  'Schull Community College, Cork County',
  'Scoil Mhuire, Cork County',
  'Scoil Mhuire, Cork County',
  'Scoil Mhuire Gan Smal, Cork County',
  'Skibbereen Community School, Cork County',
  'St Aloysius College, Cork County',
  'St Colman\'s Community College, Cork County',
  'St Fanahan\'s College, Cork County',
  'St Francis Capuchin College, Cork County',
  'St Goban\'s College, Cork County',
  'St Mary\'s High School, Cork County',
  'St Mary\'S Secondary School, Cork County',
  'St Mary\'s Secondary School, Cork County',
  'St Peter\'s Community School, Cork County',
  'St. Brogan\'s College, Cork County',
  'St Fachtna\'s - De La Salle College, Cork County',
  'Le Cheile Ballincollig, Cork County',
  'Kinsale Community School, Cork County',
  'Ardscoil Uí Urmoltaigh, Cork County',
  'Glanmire Community College, Cork County',
  'St Aloysius School, Cork City',
  'North Presentation, Cork City',
  'North Monastery Secondary School, Cork City',
  'Regina Mundi College, Cork City',
  'Scoil Mhuire, Cork City',
  'St Aidan\'s Community College, Cork City',
  'St Patricks College, Cork City',
  'St Vincent\'s Secondary School, Cork City',
  'St. Finbarr\'s Seminary, Cork City',
  'St. Angela\'s College, Cork City',
  'Ursuline Secondary School, Cork City',
  'Terence Mac Swiney Community College, Cork City',
  'Bishopstown Community School, Cork City',
  'Christ King Girls Sec. School, Cork City',
  'Gaelcholáiste Mhuire, Cork City',
  'Colaiste Daibheid, Cork City',
  'Coláiste An Spioraid Naoimh, Cork City',
  'Coláiste Chríost Rí, Cork City',
  'Deerpark C.B.S., Cork City',
  'Cork Educate Together Secondary School, Cork City',
  'Douglas Community School, Cork City',
  'Mayfield Community School, Cork City',
  'Mount Mercy College, Cork City',
  'Nagle Community College, Cork City',
  'Colaiste Stiofán Naofa, Cork City',
  'St John\'s Central College, Cork City',


 // Donegal
  'The Royal and Prior School, Donegal',
  'St. Catherine\'s Vocational School, Donegal',
  'St Eunan\'s College, Donegal',
  'St Columbas College, Donegal',
  'St Columba\'s Comprehensive School, Donegal',
  'Scoil Mhuire, Donegal',
  'Rosses Community School, Donegal',
  'Loreto Community School, Donegal',
  'Pobalscoil Ghaoth Dobhair, Donegal',
  'Pobalscoil Chloich Cheannfhaola, Donegal',
  'Mulroy College, Donegal',
  'Moville Community College, Donegal',
  'Magh Ene College, Donegal',
  'Loreto Convent, Donegal',
  'Abbey Vocational School, Donegal',
  'Gairmscoil Mhic Diarmada, Donegal',
  'Gairm Scoil Chú Uladh, Donegal',
  'Gaelcholaiste Chineal Eoighain, Donegal',
  'Vocational School, Donegal',
  'Letterkenny Vocational School, Donegal',
  'Deele College, Donegal',
  'Crana College, Donegal',
  'Coláiste Phobail Cholmcille, Donegal',
  'Choláise Cholmcille, Donegal',
  'Coláiste Ailigh, Donegal',
  'Carrick Vocational School, Donegal',
  'Carndonagh Community School, Donegal',

  // Dublin
  'Riversdale Community College, Dublin Fingal',
  'St Dominic\'s High School, Dublin Fingal',
  'Scoil Chaitriona, Dublin Fingal',
  'Skerries Community College, Dublin Fingal',
  'St Dominics College, Dublin Fingal',
  'St Finians Community College, Dublin Fingal',
  'St Joseph\'s Secondary School, Dublin Fingal',
  'St Marys Secondary School, Dublin Fingal',
  'St. Fintan\'s High School, Dublin Fingal',
  'Sutton Park School, Dublin Fingal',
  'Swords Community College, Dublin Fingal',
  'Colaiiste Choilm, Dublin Fingal',
  'Colaiste Ghlar na Mara, Dublin Fingal',
  'Scoil Phobail Chuil Mhin, Dublin Fingal',
  'Fingal Community College, Dublin Fingal',
  'GealcholÃ¡iste Reachrann, Dublin Fingal',
  'Hansfield Educate Together Secondary School, Dublin Fingal',
  'Hartstown Community School, Dublin Fingal',
  'LE CHEILE SECONDARY SCHOOL, Dublin Fingal',
  'Lusk Community College, Dublin Fingal',
  'Luttrellstown Community College, Dublin Fingal',
  'Malahide Community School, Dublin Fingal',
  'Mater Christi, Dublin Fingal',
  'Mount Sackville Secondary School, Dublin',
  'New Cross College, Dublin',
  'Pobalscoil Neasain, Dublin',
  'Portmarnock Community School, Dublin',
  'Balbriggan Community College, Dublin',
  'Belcamp College, Dublin',
  'Blakestown Community School, Dublin',
  'Castleknock College, Dublin',
  'Castleknock Community College, Dublin',
  'Chanel College, Dublin',
  'ST THOMAS SPECIAL SCH, Dublin',
  'St Vincents C.B.S. Glasnevin, Dublin',
  'St Josephs Secondary School, Dublin',
  'St. Aidan\'s C.B.S., Dublin',
  'St. David\'s C.B.S., Dublin',
  'Synge Street CBS, Dublin',
  'Terenure College, Dublin',
  'St Pauls C.B.S., Dublin',
  'The Donahies Community School, Dublin',
  'The High School, Dublin',
  'The Teresian School, Dublin',
  'Trinity Comprehensive School, Dublin',
  'Plunket College, Dublin',
  'Presentation College, Dublin',
  'Presentation College, Dublin',
  'Technical Institute, Dublin',
  'St Declan\'s College, Dublin',
  'Saint Dominic\'s Secondary School, Dublin',
  'St John Of God Secondary School, Dublin',
  'St Johns College De La Salle, Dublin',
  'St Josephs C.B.S., Dublin',
  'St Kevins College, Dublin',
  'St Louis High School, Dublin',
  'St Mary\'s Secondary School, Dublin',
  'St Marys Secondary School, Dublin',
  'St Michaels College, Dublin',
  'St Michaels Secondary School, Dublin',
  'St Patricks Cathedral G.S, Dublin',
  'St Pauls College, Dublin',
  'Grange Community College, Dublin',
  'Greendale Community School, Dublin',
  'Holy Faith Secondary School, Dublin',
  'Institute of Education, Dublin',
  'Kylemore College, Dublin',
  'Larkin Community College, Dublin',
  'Manor House, Dublin',
  'Margaret Aylward Community College, Dublin',
  'Marino College, Dublin',
  'Maryfield College, Dublin',
  'Mercy College Coolock, Dublin',
  'Mount Carmel Secondary School, Dublin',
  'Mount Temple Comprehensive School, Dublin',
  'Muckross Park College, Dublin',
  'O\'Connell School, Dublin',
  'Our Lady Of Mercy College, Dublin',
  'The Kings Hospital, Dublin',
  'Alexandra College, Dublin',
  'Meanscoil Chroimghlinne, Dublin',
  'Ardscoil La Salle, Dublin',
  'Ardscoil RÃ­s, Dublin',
  'Assumption Secondary School, Dublin',
  'Dublin North East Educate Together Secondary School, Dublin',
  'Belvedere College, Dublin',
  'Beneavin De La Salle College, Dublin',
  'Coláiste Eanna, Dublin',
  'Catholic University School, Dublin',
  'St. Kevins College, Dublin',
  'Coláiste Dhúlaigh, Dublin',
  'ColÃ¡iste Mhuire, Dublin',
  'C.B.S. James Street, Dublin',
  'C.B.S. Westland Row, Dublin',
  'Meanscoil IognÃ¡id RÃ­s, Dublin',
  'Gonzaga College, Dublin',
  'Moyle Park College, Dublin',
  'Old Bawn Community School, Dublin',
  'Presentation Brothers Glasthule, Dublin',
  'Rockbrook Park School, Dublin',
  'Rosary College, Dublin',
  'Sancta Maria College, Dublin',
  'St Aidan\'s Community School, Dublin',
  'Pobail Scoil Naomh Coilm Cille, Dublin',
  'St Columba\'s College, Dublin',
  'St Conleths College, Dublin',
  'St Josephs College, Dublin',
  'St Mac Dara\'s Community College, Dublin',
  'St Marks Community School, Dublin',
  'St Marys College, Dublin',
  'St Pauls Secondary School, Dublin',
  'St. Kevin\'s Community College, Dublin',
  'Tallaght Community School, Dublin',
  'Ballinteer/Stepaside Educate Together Secondary School, Dublin',
  'St. Tiernan\'s Community School, Dublin',
  'Ballinteer Community School, Dublin',
  'Colaiste Eanna CBS, Dublin',
  'Colaiste Chilliain, Dublin',
  'Colaiste Cois Life, Dublin',
  'Colaiste de hIde, Dublin',
  'Colaiste PhÃ¡draig CBS, Dublin',
  'Collinstown Park Community College, Dublin',
  'Deansrath Community College, Dublin',
  'Firhouse Community College, Dublin',
  'Killinarden Community School, Dublin',
  'Kishoge Community College, Dublin',
  'Loreto High School, Dublin',
  'Jobstown Community College, Dublin',
  'Booterstown Blackrock Dunlaoghaire ET, Dublin',
  'Caritas College, Dublin',
  'Clonturk Community College, Dublin',
  'Edmund Rice College Carpenterstown Castleknock, Dublin',
  'Eriu Community College, Dublin',
  'Firhouse Educate Together Secondary School, Dublin',
  'Greenhills College, Dublin',
  'Kingswood Community College, Dublin',
  'Dublin South City Educate Together Secondary School, Dublin',
  'St Seton\'s Secondary School, Dublin',
  'Rathmines College, Dublin',


 // Galway
  'Gairm Scoil Chilleáin Naofa, Galway',
  'Portumna Community School, Galway',
  'Presentation College, Galway',
  'Presentation College, Galway',
  'Presentation College, Galway',
  'Scoil Aine, Galway',
  'St. Brigid\'s School, Galway',
  'Scoil Chuimsitheach Chiaráin, Galway',
  'Scoil Phobail Mhic Dara, Galway',
  'StBrigids Vocational School, Galway',
  'St Jarlath\'s College, Galway',
  'St Jarlath\'s College, Galway',
  'St Patrick\'s College, Galway',
  'St Pauls, Galway',
  'St Raphaels College, Galway',
  'St. Cuan\'s College, Galway',
  'Seamount College, Galway',
  'Gairmscoil Einne Oileain Arann, Galway',
  'Gairmscoil Fheichin Naofa, Galway',
  'Dunmore Community School, Galway',
  'Gairmscoil na bPiarsach, Galway',
  'Colaiste Sheosaimh, Galway',
  'GLENAMADDY COMMUNITY SCHOOL, Galway',
  'Gort Community School, Galway',
  'High Cross College, Galway',
  'Holy Rosary College, Galway',
  'Mercy College, Galway',
  'Coláiste Iognáid S.J., Galway',
  'Scoil Phobail, Galway',
  'Gaelcholaiste an Eachreidh, Galway',
  'Colaiste Cholmcille, Galway',
  'Colaiste Chroi Mhuire An Spideal, Galway',
  'Colaiste Naomh Eoin, Galway',
  'St. Jarlath\'s Vocational School, Galway',
  'Colaiste Claregalway, Galway',
  'Coláiste Ghobnait, Galway',
  'Coláiste Einde, Galway',
  'Coláiste Muire Máthair, Galway',
  'Coláiste na Coiribe, Galway',
  'Dominican College, Galway',
  'Galway Community College, Galway',
  'Galway Educate Together Secondary School, Galway',
  'Meánscoil Mhuire, Galway',
  'Merlin College, Galway',
  'Our Ladys College, Galway',
  'Presentation Secondary School, Galway',
  'Jesus & Mary Secondary School, Galway',
  'St Joseph\'s College, Galway',
  'St. Mary\'s College, Galway',
  'Tuam Vocational School, Galway',
  'Calasanctius College, Galway',
  'Gairmscoil Mhuire, Galway',




// Kerry
  'The Intermediate School, Kerry',
  'Comprehensive School, Kerry',
  'St. Michael\'s College, Kerry',
  'St. Joseph\'s Secondary School, Kerry',
  'Mean Scoil Naomh Ioseph, Kerry',
  'St. Brigid\'s Secondary School, Kerry',
  'Meánscoil na Toirbhirte, Kerry',
  'Scoil Phobail Sliabh Luachra, Kerry',
  'Presentation Secondary School, Kerry',
  'Presentation Secondary School, Kerry',
  'Presentation Secondary School, Kerry',
  'Pobalscoil Inbhear Sceine, Kerry',
  'Pobailscoil Chorca Dhuibhne, Kerry',
  'Méan Scoil na mBráithre Críostaí, Kerry',
  'Mercy Secondary School, Kerry',
  'Meánscoil An Leith-Triúigh, Kerry',
  'Meanscoil Phadraig Naofa, Kerry',
  'Mean Scoil Nua an Leith Triuigh, Kerry',
  'Community College, Kerry',
  'Killarney Community College, Kerry',
  'Gaelcholáiste Chiarraí, Kerry',
  'C.B.S. The Green, Kerry',
  'Coláiste na Sceilge, Kerry',
  'Coláiste Ide, Kerry',
  'Tralee Community College, Kerry',
  'Coláiste Bhréanainn, Kerry',
  'Castleisland Community College, Kerry',
  'Listowel Community College, Kerry',
  'Causeway Comprehensive School, Kerry',


// Kildare
  'Colaiste Lorcain, Kildare',
  'Leixlip Community School, Kildare',
  'Clongowes Wood College, Kildare',
  'Celbridge Community School, Kildare',
  'Athy Community College, Kildare',
  'Ardscoil Rath Iomgháin, Kildare',
  'Scoil Mhuire, Kildare',
  'Naas Community College, Kildare',
  'Newbridge College, Kildare',
  'Patrician Secondary School, Kildare',
  'St Patrick\'s Community College, Kildare',
  'Presentation Secondary School, Kildare',
  'Salesian College, Kildare',
  'Scoil Dara, Kildare',
  'Scoil Eoin, Kildare',
  'Meánscoil Iognáid Ris, Kildare',
  'Scoil Mhuire Community School, Kildare',
  'St Conleth\'s Vocational School, Kildare',
  'St Farnan\'s Post Primary School, Kildare',
  'St Joseph\'s Academy, Kildare',
  'St Pauls Secondary School, Kildare',
  'St Wolstan\'s Community School, Kildare',
  'Coláiste Naomh Mhuire, Kildare',
  'Maynooth Post Primary School, Kildare',
  'Maynooth Community College, Kildare',
  'Ardscoil na Trionode, Kildare',
  'Vocational School, Kildare',
  'Kildare Town Community School, Kildare',
  'Holy Family Secondary School, Kildare',
  'GAEL CHOLAISTE CHILL DARA, Kildare',
  'Curragh Post-Primary School, Kildare',
  'Cross And Passion College, Kildare',
  'Confey Community College, Kildare',

  // Kilkenny
  'CBS Kilkenny',
  'Colaiste Pobail Osrai, Kilkenny',
  'Coláiste Abhainn Rí, Kilkenny',
  'Coláiste Cois Siúire, Kilkenny',
  'Coláiste Eamann Rís, Kilkenny',
  'Coláiste Mhuire, Kilkenny',
  'Duiske College, Kilkenny',
  'Grennan College, Kilkenny',
  'City Vocational School, Kilkenny',
  'Kilkenny College, Kilkenny',
  'Loreto Secondary School, Kilkenny',
  'Presentation Secondary School, Kilkenny',
  'Scoil Aireagail, Kilkenny',
  'St Kieran\'s College, Kilkenny',
  'St. Brigid\'s College, Kilkenny',
  'Community School, Kilkenny',


  // Laois
  'Holy Family Junior School, Laois',
  'Community School, Laois',
  'Mountrath Community School, Laois',
  'Patrician College, Laois',
  'Portlaoise Vocational School, Laois',
  'Scoil Chriost Ri, Laois',
  'St Fergal\'s College, Laois',
  'St. Aengus Post-Primary, Laois',
  'St. Mary\'s C.B.S., Laois',
  'Brigidine Secondary School, Laois',
  'Clonaslee Vocational School, Laois',
  'Coláiste Iosagáin, Laois',
  'Dunamase College, Laois',
  'Heywood Community School, Laois',

  // Limerick
  'Thomond Community College, Limerick',
  'Abbeyfeale Community College (Colaiste Ide agus Iosef), Limerick',
  'Colaiste Mhuire, Limerick',
  'Colaiste na Trocaire, Limerick',
  'Coláiste Ióasef, Limerick',
  'Desmond College, Limerick',
  'Glenstal Abbey School, Limerick',
  'Hazelwood College, Limerick',
  'John The Baptist Community School, Limerick',
  'Salesian Secondary College, Limerick',
  'Scoil Mhuire, Limerick',
  'Scoil Mhuire agus Ide, Limerick',
  'Scoil na Trionoide Naofa, Limerick',
  'Scoil Pól, Limerick',
  'St Fintan\'s C.B.S, Limerick',
  'St Ita\'s College, Limerick',
  'St Joseph\'s Secondary School, Limerick',
  'Coláiste Pobail Mhichíl, Limerick',
  'St. Jospeh\'s Sec. School, Limerick',
  'Vocational School, Limerick',
  'Colaiste Chiarain, Limerick',
  'Castletroy College, Limerick',
  'Ardscoil Ris, Limerick',
  'Presentation Secondary School, Limerick',
  'Crescent College Comprehensive, Limerick',
  'Colaiste Mhichil, Limerick',
  'Edmund Rice College, Limerick',
  'Gaelcholaiste Luimnigh, Limerick',
  'Laurel Hill Coláiste FCJ, Limerick',
  'Laurel Hill Secondary School FCJ, Limerick',
  'Limerick City East Secondary School, Limerick',
  'Mungret Community College, Limerick',
  'Salesian Secondary School, Limerick',
  'Scoil Carmel, Limerick',
  'St Clements College, Limerick',
  'St Endas Community School, Limerick',
  'St Munchin\'s College, Limerick',
  'St Nessan\'s Community College, Limerick',
  'Villiers Secondary School, Limerick',
  'Ard Scoil Mhuire FCJ, Limerick',
  'Ardscoil Mhuire, Limerick',
  'Limerick Senior College, Limerick',


 // Longford
  'Ballymahon Vocational School, Longford',
  'Cnoc Mhuire, Longford',
  'Lanesboro Community College, Longford',
  'Mercy Secondary School, Longford',
  'Moyne Community School, Longford',
  'Meán Scoil Muire, Longford',
  'St. Mel\'s College, Longford',
  'Templemichael College, Longford',
  'Ardscoil Phadraig, Longford',


  // Louth
  'St. Joseph\'s C.B.S., Louth',
  'St Vincent\'s Secondary School, Louth',
  'St Oliver\'s Community College, Louth',
  'St Mary\'s Diocesan School, Louth',
  'St Mary\'s College, Louth',
  'St Louis Secondary School, Louth',
  'Scoil Ui Mhuiri, Louth',
  'Sacred Heart Secondary School, Louth',
  'O Fiaich College, Louth',
  'Pobailcholaiste Chú Chulainn, Louth',
  'Our Ladys College, Louth',
  'Gaelcholaiste Dhun Dealgan, Louth',
  'Dundalk Grammar School, Louth',
  'Drogheda Grammar School, Louth',
  'Drogheda Educate Together Secondary School, Louth',
  'De La Salle Secondary School, Louth',
  'Colaiste Rís, Louth',
  'Bush Post Primary School, Louth',
  'Ballymakenny College, Louth',
  'Ardee Community School, Louth',
  'Drogheda Inst. of Further Education, Louth',


  // Mayo
  'Sacred Heart School, Mayo',
  'St. Tiernan\'s College, Mayo',
  'St. Patrick\'s College, Mayo',
  'St. Mary\'s Secondary School, Mayo',
  'St. Geralds College, Mayo',
  'St. Brendan\'s College, Mayo',
  'St Muredachs College, Mayo',
  'St Louis Community School, Mayo',
  'St Josephs Community College, Mayo',
  'St Joseph\'s Secondary School, Mayo',
  'Naomh Iosaef, Mayo',
  'Coláiste Cholmáin, Mayo',
  'Scoil Muire Agus Padraig, Mayo',
  'Scoil Damhnait, Mayo',
  'Sancta Maria College, Mayo',
  'Rice College, Mayo',
  'Our Lady\'s Secondary School, Mayo',
  'Balla Secondary School, Mayo',
  'Moyne College, Mayo',
  'Mount St Michael, Mayo',
  'McHale College, Mayo',
  'Carrowbeg College, Mayo',
  'Jesus & Mary Secondary School, Mayo',
  'Davitt College, Mayo',
  'Coláiste Mhuire, Mayo',
  'Colaiste Pobail Acla, Mayo',
  'Colaiste Chomain, Mayo',
  'Ballyhaunis Community School, Mayo',
  'Ballinrobe Community School, Mayo',

// Meath
  'Enfield Community College, Meath',
  'St Peter\'s College, Meath',
  'St Patrick\'s Classical School, Meath',
  'St Oliver Post Primary, Meath',
  'St. Joseph\'s Secondary School, Meath',
  'St Ciaran\'s Community School, Meath',
  'Scoil Mhuire, Meath',
  'Ratoath Community School, Meath',
  'O\'Carolan College, Meath',
  'Loreto Secondary School, Meath',
  'Franciscan College, Meath',
  'Eureka Secondary School, Meath',
  'Dunshaughlin ETB School, Meath',
  'Community College, Meath',
  'Coláiste Pobail Rath Cairn, Meath',
  'Colaiste na Mi, Meath',
  'De Lacy College, Meath',
  'Coláiste Clavin, Meath',
  'Laytown Community School, Meath',
  'Boyne Community School, Meath',
  'Ashbourne Community School, Meath',
  'Beaufort College, Meath',
  'ATHBOY COMMUNITY SCHOOL, Meath',

 // Monaghan
  'Ballybay Community College, Monaghan',
  'Beech Hill College, Monaghan',
  'Castleblayney College, Monaghan',
  'Coláiste Oiriall, Monaghan',
  'Inver College, Monaghan',
  'Largy College, Monaghan',
  'Monaghan Collegiate School, Monaghan',
  'Our Lady\'s Secondary School, Monaghan',
  'Patrician High School, Monaghan',
  'St Louis Secondary School, Monaghan',
  'St. Louis Secondary School, Monaghan',
  'St. Macartan\'s College, Monaghan',


// Offaly
  'Sacred Heart Secondary School, Offaly',
  'Saint Rynagh\'s Community College, Offaly',
  'St Mary\'s Secondary School, Offaly',
  'St. Brendan\'s Community School, Offaly',
  'Tullamore College, Offaly',
  'Ard Scoil Chiarain Naofa, Offaly',
  'Colaiste na Sionna, Offaly',
  'Colaiste Choilm, Offaly',
  'Coláiste Naomh Cormac, Offaly',
  'Gallen Community School, Offaly',
  'Killina Presentation Secondary School, Offaly',
  'La Sainte Union Secondary School, Offaly',
  'Oaklands Community College, Offaly',


  // Roscommon
  'Abbey Community College Boyle, Roscommon',
  'Community School, Roscommon',
  'Coláiste Chiaráin, Roscommon',
  'C.B.S. Roscommon, Roscommon',
  'Elphin Community College, Roscommon',
  'Roscommon Vocational School, Roscommon',
  'Scoil Mhuire, Roscommon',
  'Scoil Mhuire gan Smal, Roscommon',
  'St Nathy\'s College, Roscommon',

 // Sligo
  'Gurteen Vocational School, Sligo',
  'Jesus & Mary Secondary School, Sligo',
  'Mercy College, Sligo',
  'North Connaught College, Sligo',
  'Sligo Grammar School, Sligo',
  'St Attracta\'s Community School, Sligo',
  'St Marys College, Sligo',
  'Summerhill College, Sligo',
  'Ursuline College, Sligo',
  'Ballinode College, Sligo',
  'Colaiste Mhuire, Sligo',
  'Coláiste Iascaigh, Sligo',
  'Coola Vocational School, Sligo',
  'Corran College, Sligo',
  'Grange Vocational School, Sligo',


  // Tipperary
  'Ursuline Secondary School, Tipperary',
  'The Abbey School, Tipperary',
  'St. Anne\'s Secondary School, Tipperary',
  'St. Alibe\'s School, Tipperary',
  'Scoil Ruain, Tipperary',
  'Scoil Mhuire, Tipperary',
  'Rockwell College, Tipperary',
  'Central Technical Institute, Tipperary',
  'Presentation Secondary School, Tipperary',
  'Patrician Presentation, Tipperary',
  'Loreto Secondary School, Tipperary',
  'C.B.S., Tipperary',
  'Vocational School, Tipperary',
  'Colaiste Dun Iascaigh, Tipperary',
  'Ardscoil na mBráithre, Tipperary',
  'Cashel Community School, Tipperary',
  'St. Sheelan\'s College, Tipperary',
  'St. Mary\'s Secondary School, Tipperary',
  'St. Joseph\'s C.B.S, Tipperary',
  'St Mary\'s Secondary School, Tipperary',
  'Borrisokane Community College, Tipperary',
  'St Josephs College, Tipperary',
  'Presentation Secondary School, Tipperary',
  'Our Ladys Secondary School, Tipperary',
  'St Joseph\'s College, Tipperary',
  'Nenagh Vocational School, Tipperary',
  'C.B.S. Thurles, Tipperary',
  'Colaiste Phobáil Rós Cré, Tipperary',
  'Cistercian College, Tipperary',

  // Waterford
  'Waterpark College, Waterford',
  'Stella Maris, Waterford',
  'St Declan\'s Community College, Waterford',
  'St Augustines College, Waterford',
  'Meánscoil San Nioclás, Waterford',
  'Scoil na mBraithre, Waterford',
  'C.B.S. Tramore, Waterford',
  'Coláiste Chathail Naofa, Waterford',
  'BLACKWATER COMMUNITY SCHOOL, Waterford',
  'Ard Scoil na nDeise, Waterford',
  'Ard Scoil na Mara, Waterford',
  'St Paul\'s Community College, Waterford',
  'St Angela\'s, Waterford',
  'Our Lady Of Mercy Secondary School, Waterford',
  'Newtown School, Waterford',
  'C.B.S. Mount Sion, Waterford',
  'Gaelcholaiste Portlairge, Waterford',
  'Central Technical Institute, Waterford',


  // Westmeath
  'Athlone Community College, Westmeath',
  'Castlepollard Community College, Westmeath',
  'Colaiste Mhuire, Westmeath',
  'Columba College, Westmeath',
  'Loreto College, Westmeath',
  'Marist College, Westmeath',
  'Meán Scoil an Chlochair, Westmeath',
  'Moate Community School, Westmeath',
  'Mullingar Community College, Westmeath',
  'Our Lady\'s Bower, Westmeath',
  'St Aloysius College, Westmeath',
  'St Finian\'s College, Westmeath',
  'St Joseph\'s College, Westmeath',
  'St Joseph\'s Secondary School, Westmeath',
  'Wilson\'s Hospital School, Westmeath',


  // Wexford
  'Gorey ET, Wexford',
  'Christian Brothers Secondary School, Wexford',
  'St. Mary\'s Secondary School, Wexford',
  'St. Mary\'s C.B.S., Wexford',
  'St Peter\'s College, Wexford',
  'Wexford Vocational College, Wexford',
  'Ramsgrange Community School, Wexford',
  'Presentation Secondary School, Wexford',
  'Our Lady of Lourdes Secondary School, Wexford',
  'Meanscoil Garman, Wexford',
  'Loreto Secondary School, Wexford',
  'New Ross Vocational College, Wexford',
  'Gorey Community School, Wexford',
  'Good Counsel College, Wexford',
  'F.C.J. Secondary School, Wexford',
  'Vocational College, Wexford',
  'Gorey Community College, Wexford',
  'Coláiste Bride, Wexford',
  'Bridgetown Vocational College, Wexford',
  'Kilmuckridge Vocational College, Wexford',
  'Coláiste Abbain, Wexford',
  'Vocational College Bunclody, Wexford',


  // Wicklow
  'Wicklow Educate Together Secondary School, Wicklow',
  'Temple Carrig Secondary School, Wicklow',
  'St. Killian\'s Community School, Wicklow',
  'St David\'s Secondary, Wicklow',
  'St Marys College, Wicklow',
  'Greystones Community College, Wicklow',
  'St Kevin\'s Community College, Wicklow',
  'St Gerard\'s, Wicklow',
  'St Brendan\'s College, Wicklow',
  'Scoil Chonglais, Wicklow',
  'Presentation College, Wicklow',
  'Our Lady\'s School, Wicklow',
  'North Wicklow Educate Together Secondary School, Wicklow',
  'Loreto Secondary School, Wicklow',
  'Arklow Community College, Wicklow',
  'Gaelcholaiste na Mara, Wicklow',
  'East Glendalough School, Wicklow',
  'Dominican College, Wicklow',
  'De La Salle College, Wicklow',
  'Coláiste Raithín, Wicklow',
  'Coláiste Bhríde, Wicklow',
  'Colaiste Chraobh Abhann, Wicklow',
  'St Josephs Abbey, Wicklow',
  'Blessington Community College, Wicklow',
  'Avondale Community College, Wicklow',
  'St Kevin\'s CBS, Wicklow',
  'Abbey Community College, Wicklow',

];

export const INTERESTS = [
  'Music',
  'Sports',
  'Reading',
  'Travel',
  'Cooking',
  'Photography',
  'Art',
  'Dancing',
  'Gaming',
  'Fitness',
  'Movies',
  'Fashion',
  'Technology',
  'Nature',
  'Food',
  'Writing',
  'Pets',
  'Volunteering',
  'Languages',
  'Science',
  'History',
  'Politics',
  'Business',
  'Environment',
  'Health',
];

export const PROFILE_PROMPTS = [
  'My ideal first date is...',
  'I\'m looking for someone who...',
  'My biggest fear is...',
  'My most controversial opinion is...',
  'I get way too excited about...',
  'My friends would describe me as...',
  'My biggest ick is...',
  'I\'m a firm believer that...',
  'My most irrational fear is...',
  'I\'m the type of person who...',
  'My love language is...',
  'I\'m passionate about...',
  'My biggest flex is...',
  'I\'m looking for someone who can...',
  'My most used emoji is...',
];


export const LOOKING_FOR_OPTIONS = [
  { id: 'swaps', label: 'Swaps' },
  { id: 'go_to_someones_debs', label: 'Go to someone\'s debs' },
  { id: 'bring_someone_to_my_debs', label: 'Bring someone to my debs' }
];

export const INTENTIONS_OPTIONS = [
  { id: 'one_night_thing', label: 'One night thing', emoji: '🌙' },
  { id: 'short_term_only', label: 'Short term only', emoji: '💝' },
  { id: 'short_term_but_open_to_long_term', label: 'Short term but open to long term', emoji: '🎭' },
  { id: 'long_term_only', label: 'Long term only', emoji: '💍' },
  { id: 'long_term_but_open_to_short_term', label: 'Long term but open to short term', emoji: '💕' },
  { id: 'friends', label: 'Friends', emoji: '👥' }
];

export const RELATIONSHIP_STATUS_OPTIONS = [
  { id: 'single', label: 'Single', emoji: '😊' },
  { id: 'relationship', label: 'In a relationship', emoji: '💑' },
  { id: 'complicated', label: 'It\'s complicated', emoji: '🤷‍♀️' }
];

export const PROMPT_CATEGORIES = [
  { id: 'about-me', label: 'About Me', icon: 'person' },
  { id: 'personality', label: 'Personality', icon: 'sparkles' },
  { id: 'lifestyle', label: 'Lifestyle', icon: 'star' },
  { id: 'relationships', label: 'Relationships', icon: 'heart' },
  { id: 'fun', label: 'Fun & Quirky', icon: 'happy' },
  { id: 'goals', label: 'Goals & Dreams', icon: 'flag' },
  { id: 'favorites', label: 'Favorites', icon: 'heart' },
  { id: 'random', label: 'Random Facts', icon: 'dice' },
];

export const ALL_PROMPTS = {
  'about-me': [
    'I am...',
    'My friends would describe me as...',
    'I get way too excited about...',
    'My most controversial opinion is...',
    'I\'m looking for someone who...',
    'My ideal Sunday is...',
    'I\'m a firm believer that...',
    'My biggest fear is...',
    'My most grateful for...',
    'My love language is...',
  ],
  'personality': [
    'I\'m the type of person who...',
    'My personality type is...',
    'I\'m most confident when...',
    'I\'m working on...',
    'My biggest strength is...',
    'My biggest weakness is...',
    'I\'m most passionate about...',
    'I\'m most competitive about...',
    'I\'m most patient with...',
    'I\'m most impatient with...',
  ],
  'lifestyle': [
    'My typical day looks like...',
    'I spend most of my money on...',
    'My morning routine is...',
    'My evening routine is...',
    'I\'m most productive when...',
    'My guilty pleasure is...',
    'My self-care routine includes...',
    'I\'m most organized about...',
    'I\'m most spontaneous about...',
    'My comfort zone is...',
  ],
  'relationships': [
    'Dating me is like...',
    'I\'m looking for someone who...',
    'My ideal first date is...',
    'I\'m most attracted to people who...',
    'My relationship deal-breakers are...',
    'I show love by...',
    'I receive love through...',
    'My relationship goals are...',
    'I\'m most romantic when...',
    'My love story would be...',
  ],
  'fun': [
    'My most irrational fear is...',
    'My most controversial take is...',
    'I go crazy for...',
    'My most embarrassing moment was...',
    'My most random skill is...',
    'I\'m most likely to...',
    'My most unpopular opinion is...',
    'I\'m most competitive about...',
    'My most random fact is...',
    'I\'m most likely to get in trouble for...',
  ],
  'goals': [
    'This year, I really want to...',
    'My biggest goal is...',
    'In 5 years, I see myself...',
    'My bucket list includes...',
    'I\'m most proud of...',
    'My biggest achievement is...',
    'I\'m working towards...',
    'My dream job is...',
    'My biggest challenge is...',
    'I\'m most motivated by...',
  ],
  'favorites': [
    'My favorite way to spend a weekend is...',
    'My favorite book is...',
    'My favorite movie is...',
    'My favorite food is...',
    'My favorite place is...',
    'My favorite season is...',
    'My favorite holiday is...',
    'My favorite way to exercise is...',
    'My favorite way to relax is...',
    'My favorite way to celebrate is...',
  ],
  'random': [
    'A random fact I love is...',
    'My most useless talent is...',
    'I recently discovered that...',
    'My most random memory is...',
    'I\'m most likely to...',
    'My most random thought today was...',
    'I\'m most curious about...',
    'My most random hobby is...',
    'I\'m most likely to get distracted by...',
    'My most random fear is...',
  ],
};

export const COUNTIES = [
  'Carlow',
  'Cavan',
  'Clare',
  'Cork',
  'Donegal',
  'Dublin',
  'Galway',
  'Kerry',
  'Kildare',
  'Kilkenny',
  'Laois',
  'Leitrim',
  'Limerick',
  'Longford',
  'Louth',
  'Mayo',
  'Meath',
  'Monaghan',
  'Offaly',
  'Roscommon',
  'Sligo',
  'Tipperary',
  'Waterford',
  'Westmeath',
  'Wexford',
  'Wicklow',
];

// Design System Spacing Tokens
export const SPACING = {
  xs: 4,    // 4px
  sm: 8,    // 8px
  md: 16,   // 16px
  lg: 24,   // 24px
  xl: 32,   // 32px
  '2xl': 48, // 48px
  '3xl': 64, // 64px
} as const;

// Design System Border Radius Tokens
export const BORDER_RADIUS = {
  sm: 8,    // 8px
  md: 12,   // 12px
  lg: 16,   // 16px
  xl: 20,   // 20px
  '2xl': 24, // 24px
} as const;
